### ISSUE TITLE
Crash after allowing permission

### ISSUE THREAD

**Issue by kaetemi** [BaseflowIT/flutter-geolocator#129]
Flutter 0.9.4

Calling `_geolocator.getPositionStream().listen(...);`
Followed immediately by `await _geolocator.getLastKnownPosition();`
Same when doing the reverse.

Crashes after allowing permission.

```
I/Timeline(26084): Timeline: Activity_launch_request time:146739940 intent:Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller (has extras) }
W/Activity(26084): Can reqeust only one set of permissions at a time
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): Failed to handle method call
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:174)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at com.baseflow.permissionhandler.PermissionHandlerPlugin.processResult(PermissionHandlerPlugin.kt:286)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at com.baseflow.permissionhandler.PermissionHandlerPlugin.handlePermissionsRequest(PermissionHandlerPlugin.kt:278)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at com.baseflow.permissionhandler.PermissionHandlerPlugin.access$handlePermissionsRequest(PermissionHandlerPlugin.kt:27)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at com.baseflow.permissionhandler.PermissionHandlerPlugin$Companion$registerWith$1.onRequestPermissionsResult(PermissionHandlerPlugin.kt:45)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:191)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:125)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:133)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at android.app.Activity.requestPermissions(Activity.java:4290)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:507)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at com.baseflow.permissionhandler.PermissionHandlerPlugin.requestPermissions(PermissionHandlerPlugin.kt:235)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at com.baseflow.permissionhandler.PermissionHandlerPlugin.onMethodCall(PermissionHandlerPlugin.kt:114)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at android.app.ActivityThread.main(ActivityThread.java:6383)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/MethodChannel#flutter.baseflow.com/permissions/methods(26084): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
E/FlutterNativeView(26084): Uncaught exception in binary message listener
E/FlutterNativeView(26084): java.lang.IllegalStateException: Reply already submitted
E/FlutterNativeView(26084): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:174)
E/FlutterNativeView(26084): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:209)
E/FlutterNativeView(26084): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/FlutterNativeView(26084): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/FlutterNativeView(26084): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/FlutterNativeView(26084): 	at android.os.Looper.loop(Looper.java:142)
E/FlutterNativeView(26084): 	at android.app.ActivityThread.main(ActivityThread.java:6383)
E/FlutterNativeView(26084): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterNativeView(26084): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/FlutterNativeView(26084): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
D/AndroidRuntime(26084): Shutting down VM
E/AndroidRuntime(26084): FATAL EXCEPTION: main
E/AndroidRuntime(26084): Process: app.infmarketplace, PID: 26084
E/AndroidRuntime(26084): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=25, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {app.infmarketplace/app.infmarketplace.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(26084): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4221)
E/AndroidRuntime(26084): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4264)
E/AndroidRuntime(26084): 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
E/AndroidRuntime(26084): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613)
E/AndroidRuntime(26084): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(26084): 	at android.os.Looper.loop(Looper.java:163)
E/AndroidRuntime(26084): 	at android.app.ActivityThread.main(ActivityThread.java:6383)
E/AndroidRuntime(26084): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26084): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(26084): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
E/AndroidRuntime(26084): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(26084): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:174)
E/AndroidRuntime(26084): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
E/AndroidRuntime(26084): 	at com.baseflow.permissionhandler.PermissionHandlerPlugin.processResult(PermissionHandlerPlugin.kt:286)
E/AndroidRuntime(26084): 	at com.baseflow.permissionhandler.PermissionHandlerPlugin.handlePermissionsRequest(PermissionHandlerPlugin.kt:278)
E/AndroidRuntime(26084): 	at com.baseflow.permissionhandler.PermissionHandlerPlugin.access$handlePermissionsRequest(PermissionHandlerPlugin.kt:27)
E/AndroidRuntime(26084): 	at com.baseflow.permissionhandler.PermissionHandlerPlugin$Companion$registerWith$1.onRequestPermissionsResult(PermissionHandlerPlugin.kt:45)
E/AndroidRuntime(26084): 	at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:191)
E/AndroidRuntime(26084): 	at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:125)
E/AndroidRuntime(26084): 	at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:133)
E/AndroidRuntime(26084): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7277)
E/AndroidRuntime(26084): 	at android.app.Activity.dispatchActivityResult(Activity.java:7129)
E/AndroidRuntime(26084): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4217)
E/AndroidRuntime(26084): 	... 9 more
I/Process (26084): Sending signal. PID: 26084 SIG: 9
Lost connection to device.
Exited (sigterm)
```

**Comment by Siddharth-IITH** [comment]
I am facing the same issue.

[ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
    MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)
    <asynchronous suspension>
    #1      PermissionHandler.checkPermissionStatus (package:permission_handler/permission_handler.dart:35:49)
    <asynchronous suspension>
    #2      Geolocator._getLocationPermission (package:geolocator/geolocator.dart:180:10)
    <asynchronous suspension>
    #3      Geolocator.getCurrentPosition (package:geolocator/geolocator.dart:88:47)
    <asynchronous suspension>
    #4      checkGps (package:gpsmessage/main.dart:124:8)
    <asynchronous suspension>
    #5      _MyHomePageState._incrementCounter.<anonymous closure> (package:gpsmessage/main.dart:65:7)
    #6      State.setState (package:flutter/src/widgets/framework.dart:1130:30)
    #7      _MyHomePageState._incrementCounter (package:gpsmessage/main.dart:57:5)
    #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
    #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
    #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
    #11     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
    #12     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
    #13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
    #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:184:20)
    #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
    #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
    #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
    #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
    #19     _invoke1 (dart:ui/hooks.dart:168:13)
    #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
2018-12-13 23:48:04.293 1442-2340/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 5041021 , only wrote 5040720
2018-12-13 23:48:05.483 1815-1860/system_process E/BatteryExternalStatsWorker: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
2018-12-13 23:48:07.419 1442-2340/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 5190785 , only wrote 5190480
2018-12-13 23:48:07.500 1442-1694/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 5196927 , only wrote 5194080
2018-12-13 23:48:55.284 1454-1454/? I/boot-pipe: done populating /dev/random
2018-12-13 23:48:55.817 1595-1618/? E/storaged: getDiskStats failed with result 0x1 and size 0

**Comment by WillemMali** [comment]
I'm facing what resembles the previous poster's issue:

```
E/flutter ( 4636): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 4636): MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)
E/flutter ( 4636): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)
E/flutter ( 4636): <asynchronous suspension>
E/flutter ( 4636): #1      PermissionHandler.checkPermissionStatus (package:permission_handler/permission_handler.dart:35:49)
E/flutter ( 4636): <asynchronous suspension>
E/flutter ( 4636): #2      Geolocator._getLocationPermission (package:geolocator/geolocator.dart:180:10)
E/flutter ( 4636): <asynchronous suspension>
E/flutter ( 4636): #3      Geolocator.getCurrentPosition (package:geolocator/geolocator.dart:88:47)
E/flutter ( 4636): <asynchronous suspension>
E/flutter ( 4636): #4      MapModel.centerMapOnMe (package:app/models/mapModel.dart:23:38)
E/flutter ( 4636): <asynchronous suspension>
E/flutter ( 4636): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter ( 4636): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter ( 4636): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter ( 4636): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter ( 4636): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter ( 4636): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter ( 4636): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter ( 4636): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter ( 4636): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
E/flutter ( 4636): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
E/flutter ( 4636): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
E/flutter ( 4636): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 4636): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter ( 4636): #18     _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter ( 4636): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
```

I'm using Android Studio on Debian 9, installed Flutter from source and updated it to the stable release every day. I'm using an x86 Android emulator without HVM and I've checked that the Android permissions are set correctly.

I can build from source but it's my first week using Flutter and Dart, any tips (like how the implementation is chosen) are appreciated.

**Comment by ramesh-emandi** [comment]
Is this fixed in upcoming versions?
