### ISSUE TITLE
Plugin fails together with android_alarm_manager

### ISSUE THREAD

**Issue by marcmo** [BaseflowIT/flutter-geolocator#175]
### Current behavior
I have a problem similar to #82 . When trying to use this plugin on android at the same time as android_alarm_manager, the app will crash at startup with an unhandled exception since the activity is null.
In closing #82 you replaced `activity` with `context` which took care of this. Now you depend on your `google-api-availability` plugin which again uses the activity and it fails again.

I tested without passing the activity but the context [here](https://github.com/marcmo/flutter-geolocator) and [here](https://github.com/marcmo/flutter-google-api-availability) and the crash does not happen.

Any idea how to prevent this crash without changing `google-api-availability`?

```
E/MethodChannel#plugins.flutter.io/android_alarm_manager: Failed to handle method call
    java.lang.IllegalStateException: registrar.activity() must not be null
        at com.baseflow.googleapiavailability.GoogleApiAvailabilityPlugin$Companion.registerWith(GoogleApiAvailabilityPlugin.kt:22)
        at com.baseflow.googleapiavailability.GoogleApiAvailabilityPlugin.registerWith(Unknown Source:18)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:31)
        at com.esrlabs.letmein.Application.registerWith(Application.java:17)
        at io.flutter.plugins.androidalarmmanager.AlarmReceiver.startAlarmService(AlarmReceiver.java:64)
        at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.startService(AndroidAlarmManagerPlugin.java:75)
        at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.onMethodCall(AndroidAlarmManagerPlugin.java:52)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
        at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2019-01-28 11:58:11.246 2499-2567/com.esrlabs.letmein E/flutter: [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
    PlatformException(error, registrar.activity() must not be null, null)
```

### Reproduction steps

Use both `android_alarm_manager` and `flutter-geolocator`. App will crash in `GeneratedPluginRegistrant`.

### Configuration

**Version:** 2.1.1

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android

**Comment by mvanbeusekom** [comment]
This problem was caused because the Geolocator used the wrong android context and should be fixed in version 5.0.0
