### ISSUE TITLE
Map Crashes on Samsungs

### ISSUE THREAD

**Issue by kasonde** [BaseflowIT/flutter-geolocator#198]
### Old (and correct) behavior
Map works fine
### Current behavior
I see this in the console
```
E/AndroidRuntime(31324): FATAL EXCEPTION: Thread-7
E/AndroidRuntime(31324): Process: com.smartech.app.smartsaverzambia.smartsaverzambia, PID: 31324
E/AndroidRuntime(31324): java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
E/AndroidRuntime(31324): 	at fb.b(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):3)
E/AndroidRuntime(31324): 	at fa.a(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):3)
E/AndroidRuntime(31324): 	at fc.a(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):15)
E/AndroidRuntime(31324): 	at com.google.maps.api.android.lib6.drd.al.a(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):6)
E/AndroidRuntime(31324): 	at ee.a(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):23)
E/AndroidRuntime(31324): 	at ee.run(:com.google.android.gms.dynamite_mapsdynamite@15090081@15.0.90 (100400-231259764):8)
E/AndroidRuntime(31324): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/00000059/MapsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000059/MapsDynamite.apk!/lib/arm64-v8a, /system/lib64]]
E/AndroidRuntime(31324): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(31324): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(31324): 	at ad.loadClass(:com.google.android.gms.dynamite_dynamiteloader@15090081@15.0.90 (100400-231259764):4)
E/AndroidRuntime(31324): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(31324): 	... 6 more
D/ViewRootImpl@f5bd31a[MainActivity](31324): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(31324): prepareNavigationBarInfo() DecorView@486fe4b[MainActivity]
D/InputMethodManager(31324): getNavigationBarColor() -855310
I/Process (31324): Sending signal. PID: 31324 SIG: 9
Lost connection to device.
```
### Reproduction steps
Install geolocator and just run the plugin
### Configuration

**Version:** Latest

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by lzgrzebski** [comment]
same here

**Comment by StijnWoerkom** [comment]
Sorry for the long wait. Do you still experience this issue? Could you tell me which version you are using of geolocator and on which model from Samsung?

**Comment by StijnWoerkom** [comment]
@lzgrzebski I reproduced the issue as described above and did not receive any issues on a Samsung or IOS device. Could you provide me with some details of your problem?

**Comment by lzgrzebski** [comment]
I'll try to run it again during the weekend, my phone is s10e, and tbh I just switched to other location package shortly after that but can try to revert it and will let you know if it still happening

**Comment by StijnWoerkom** [comment]
@lzgrzebski Thank you for your response. I will await your review and then decide if it is still relevant to investigate more into this issue or to close it.

**Comment by dauda1995** [comment]
experienced this
