### ISSUE TITLE
App crashes on Geolocator().getCurrentPosition

### ISSUE THREAD

**Issue by aleksvujic** [BaseflowIT/flutter-geolocator#288]
### Expected behavior
Expected behavior is obviously that application doesn't crash when calling `Geolocator().getCurrentPosition(...)`.

I get the following errror:

```
I/zygote64(19632): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.common.SupportErrorDialogFragment>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/DialogFragment;
I/zygote64(19632):   at com.google.android.gms.common.GoogleApiAvailability com.google.android.gms.common.GoogleApiAvailability.getInstance() ((null):1)
I/zygote64(19632):   at void com.baseflow.googleapiavailability.GoogleApiAvailabilityPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (GoogleApiAvailabilityPlugin.java:64)
I/zygote64(19632):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:201)
I/zygote64(19632):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, byte[], int) (DartMessenger.java:88)
I/zygote64(19632):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:219)
I/zygote64(19632):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/zygote64(19632):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:325)
I/zygote64(19632):   at void android.os.Looper.loop() (Looper.java:142)
I/zygote64(19632):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
I/zygote64(19632):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(19632):   at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
I/zygote64(19632):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
I/zygote64(19632): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.DialogFragment" on path: DexPathList[[zip file "/data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/base.apk"],nativeLibraryDirectories=[/data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/lib/x86_64, /data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/base.apk!/lib/x86_64, /system/lib64, /vendor/lib64]]
I/zygote64(19632):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:93)
I/zygote64(19632):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote64(19632):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote64(19632):   at com.google.android.gms.common.GoogleApiAvailability com.google.android.gms.common.GoogleApiAvailability.getInstance() ((null):1)
I/zygote64(19632):   at void com.baseflow.googleapiavailability.GoogleApiAvailabilityPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (GoogleApiAvailabilityPlugin.java:64)
I/zygote64(19632):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:201)
I/zygote64(19632):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, byte[], int) (DartMessenger.java:88)
I/zygote64(19632):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:219)
I/zygote64(19632):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/zygote64(19632):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:325)
I/zygote64(19632):   at void android.os.Looper.loop() (Looper.java:142)
I/zygote64(19632):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
I/zygote64(19632):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(19632):   at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
I/zygote64(19632):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
I/zygote64(19632): 
I/zygote64(19632): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.common.SupportErrorDialogFragment>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/DialogFragment;
I/zygote64(19632):   at com.google.android.gms.common.GoogleApiAvailability com.google.android.gms.common.GoogleApiAvailability.getInstance() ((null):1)
I/zygote64(19632):   at void com.baseflow.googleapiavailability.GoogleApiAvailabilityPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (GoogleApiAvailabilityPlugin.java:64)
I/zygote64(19632):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:201)
I/zygote64(19632):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, byte[], int) (DartMessenger.java:88)
I/zygote64(19632):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:219)
I/zygote64(19632):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/zygote64(19632):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:325)
I/zygote64(19632):   at void android.os.Looper.loop() (Looper.java:142)
I/zygote64(19632):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
I/zygote64(19632):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(19632):   at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
I/zygote64(19632):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
I/zygote64(19632): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.DialogFragment" on path: DexPathList[[zip file "/data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/base.apk"],nativeLibraryDirectories=[/data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/lib/x86_64, /data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/base.apk!/lib/x86_64, /system/lib64, /vendor/lib64]]
I/zygote64(19632):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:93)
I/zygote64(19632):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote64(19632):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote64(19632):   at com.google.android.gms.common.GoogleApiAvailability com.google.android.gms.common.GoogleApiAvailability.getInstance() ((null):1)
I/zygote64(19632):   at void com.baseflow.googleapiavailability.GoogleApiAvailabilityPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (GoogleApiAvailabilityPlugin.java:64)
I/zygote64(19632):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:201)
I/zygote64(19632):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, byte[], int) (DartMessenger.java:88)
I/zygote64(19632):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:219)
I/zygote64(19632):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/zygote64(19632):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:325)
I/zygote64(19632):   at void android.os.Looper.loop() (Looper.java:142)
I/zygote64(19632):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
I/zygote64(19632):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(19632):   at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
I/zygote64(19632):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
I/zygote64(19632): 
I/zygote64(19632): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.common.SupportErrorDialogFragment>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/DialogFragment;
I/zygote64(19632):   at com.google.android.gms.common.GoogleApiAvailability com.google.android.gms.common.GoogleApiAvailability.getInstance() ((null):1)
I/zygote64(19632):   at void com.baseflow.googleapiavailability.GoogleApiAvailabilityPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (GoogleApiAvailabilityPlugin.java:64)
I/zygote64(19632):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:201)
I/zygote64(19632):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, byte[], int) (DartMessenger.java:88)
I/zygote64(19632):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:219)
I/zygote64(19632):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/zygote64(19632):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:325)
I/zygote64(19632):   at void android.os.Looper.loop() (Looper.java:142)
I/zygote64(19632):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
I/zygote64(19632):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(19632):   at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
I/zygote64(19632):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
I/zygote64(19632): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.DialogFragment" on path: DexPathList[[zip file "/data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/base.apk"],nativeLibraryDirectories=[/data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/lib/x86_64, /data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/base.apk!/lib/x86_64, /system/lib64, /vendor/lib64]]
I/zygote64(19632):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:93)
I/zygote64(19632):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote64(19632):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote64(19632):   at com.google.android.gms.common.GoogleApiAvailability com.google.android.gms.common.GoogleApiAvailability.getInstance() ((null):1)
I/zygote64(19632):   at void com.baseflow.googleapiavailability.GoogleApiAvailabilityPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (GoogleApiAvailabilityPlugin.java:64)
I/zygote64(19632):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:201)
I/zygote64(19632):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, byte[], int) (DartMessenger.java:88)
I/zygote64(19632):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:219)
I/zygote64(19632):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/zygote64(19632):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:325)
I/zygote64(19632):   at void android.os.Looper.loop() (Looper.java:142)
I/zygote64(19632):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
I/zygote64(19632):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(19632):   at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
I/zygote64(19632):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
I/zygote64(19632): 
E/flutter (19632): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArraySet;
E/flutter (19632): 	at com.google.android.gms.common.api.internal.GoogleApiManager.<init>(Unknown Source:29)
E/flutter (19632): 	at com.google.android.gms.common.api.internal.GoogleApiManager.zab(Unknown Source:8)
E/flutter (19632): 	at com.google.android.gms.common.api.GoogleApi.<init>(Unknown Source:44)
E/flutter (19632): 	at com.google.android.gms.common.api.GoogleApi.<init>(Unknown Source:53)
E/flutter (19632): 	at com.google.android.gms.location.FusedLocationProviderClient.<init>(Unknown Source:8)
E/flutter (19632): 	at com.google.android.gms.location.LocationServices.getFusedLocationProviderClient(Unknown Source:2)
E/flutter (19632): 	at com.baseflow.geolocator.tasks.LocationUpdatesUsingLocationServicesTask.<init>(LocationUpdatesUsingLocationServicesTask.java:29)
E/flutter (19632): 	at com.baseflow.geolocator.tasks.TaskFactory.createCurrentLocationTask(TaskFactory.java:44)
E/flutter (19632): 	at com.baseflow.geolocator.GeolocatorPlugin.onMethodCall(GeolocatorPlugin.java:66)
E/flutter (19632): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/flutter (19632): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/flutter (19632): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/flutter (19632): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (19632): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/flutter (19632): 	at android.os.Looper.loop(Looper.java:142)
E/flutter (19632): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
E/flutter (19632): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (19632): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/flutter (19632): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
E/flutter (19632): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArraySet" on path: DexPathList[[zip file "/data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/base.apk"],nativeLibraryDirectories=[/data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/lib/x86_64, /data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/base.apk!/lib/x86_64, /system/lib64, /vendor/lib64]]
E/flutter (19632): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
E/flutter (19632): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/flutter (19632): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/flutter (19632): 	... 19 more
E/flutter (19632): 
F/flutter (19632): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env). 
F/libc    (19632): Fatal signal 6 (SIGABRT), code -6 in tid 19632 (.fri.food_diary)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Android/sdk_gphone_x86_64/generic_x86_64:8.0.0/OSR1.180418.007/5071102:userdebug/dev-keys'
Revision: '0'
ABI: 'x86_64'
pid: 19632, tid: 19632, name: .fri.food_diary  >>> si.lj.uni.fri.food_diary <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env). 
'
    rax 0000000000000000  rbx 0000000000004cb0  rcx ffffffffffffffff  rdx 0000000000000006
    rsi 0000000000004cb0  rdi 0000000000004cb0
    r8  000077f49603c270  r9  000077f49603c270  r10 0000000000000008  r11 0000000000000206
    r12 000077f4960d6380  r13 00007ffcfc9454c0  r14 0000000000004cb0  r15 00007ffcfc945288
    cs  0000000000000033  ss  000000000000002b
    rip 000077f49a63b817  rbp 0000000000000007  rsp 00007ffcfc945258  eflags 0000000000000206
backtrace:
    #00 pc 000000000007a817  /system/lib64/libc.so (tgkill+7)
    #01 pc 000000000002779e  /system/lib64/libc.so (abort+94)
    #02 pc 0000000000d8f8cc  /data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/lib/x86_64/libflutter.so (offset 0xd7c000)
    #03 pc 0000000000d82d9d  /data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/lib/x86_64/libflutter.so (offset 0xd7c000)
    #04 pc 0000000000d81403  /data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/lib/x86_64/libflutter.so (offset 0xd7c000)
    #05 pc 0000000000dc366e  /data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/lib/x86_64/libflutter.so (offset 0xd7c000)
    #06 pc 0000000000d90222  /data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/lib/x86_64/libflutter.so (offset 0xd7c000)
    #07 pc 0000000000d93ba0  /data/app/si.lj.uni.fri.food_diary-t_zfIfwMojz_OpR0zFKZJA==/lib/x86_64/libflutter.so (offset 0xd7c000)
    #08 pc 00000000000160b4  /system/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+884)
    #09 pc 0000000000015cae  /system/lib64/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+94)
    #10 pc 000000000011bc35  /system/lib64/libandroid_runtime.so (_ZN7androidL38android_os_MessageQueue_nativePollOnceEP7_JNIEnvP8_jobjectli+37)
    #11 pc 00000000007c90eb  /system/framework/x86_64/boot-framework.oat (offset 0x5e6000) (android.app.NativeActivity.onWindowFocusChangedNative [DEDUPED]+187)
    #12 pc 000000000000203a  /dev/ashmem/dalvik-jit-code-cache (deleted)
```

### Reproduction steps

Use the following code:

```
Future<String> _getUserLocation() async {
  Position position = await Geolocator().getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
  return 'lat: ${position.latitude}, lon: ${position.longitude}';
}

RaisedButton(
  child: Text('Enter restaurant manually'),
  onPressed: () {
    _getUserLocation().then((String value) => print(value));
  },
),
```

### Configuration

**Version:**
- Geolocator: ^5.0.0
- Flutter: 1.5.4-hotfix.2
- Dart: 2.3.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by aleksvujic** [comment]
I solved the issue by following the official documentation about migrating to AndroidX. Hope it helps someone.

[https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility](url)
