### ISSUE TITLE
Crash at startup 5.1.1

### ISSUE THREAD

**Issue by Gioxxy** [BaseflowIT/flutter-geolocator#308]
## 🐛 Bug Report

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6676)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6206)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6112)
        at android.app.ActivityThread.access$1300(ActivityThread.java:209)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1790)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6954)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbq" on path: DexPathList[[zip file "/data/app/app.eppy.eppy-PiicGERKZ3-J4hb-cm5fng==/base.apk"],nativeLibraryDirectories=[/data/app/app.eppy.eppy-PiicGERKZ3-J4hb-cm5fng==/lib/arm64, /data/app/app.eppy.eppy-PiicGERKZ3-J4hb-cm5fng==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6676) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6206) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6112) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:209) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1790) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6954) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 

### Behavior
The app crashes at startup
### Reproduction steps

Add geolocator: ^5.1.1
Add android.enableJetifier=true and android.useAndroidX=true
Run

### Configuration

**Version:** 5.1.1

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by sjoerd0301** [comment]
Hi,

In your stacktrace it shows that you have trouble with either "com.google.android.gms.common.*" which contain utility classes for Google Play services or with firebase.
If you run the example provided with the package you'll see that it runs without issue.

Could you verify whether it is the google play api's, firebase or geolocator? (please test on a real device, not an emulator.)
If it still doesn't work, please send us a complete example where we can test what is wrong.

**Comment by Gioxxy** [comment]
I solved by adding this to the end of app/build.gradle

```
allprojects {
    repositories {
        //start here
        configurations.all {
            resolutionStrategy.eachDependency { DependencyResolveDetails details ->
                def requested = details.requested
                if (requested.group == 'com.google.android.gms') {
                    details.useVersion '12.0.1'
                }
                if (requested.group == 'com.google.firebase') {
                    details.useVersion '12.0.1'
                }
            }
        }
        //end
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}
```

I'm not using firebase

**Comment by DanielCardona** [comment]
> I solved by adding this to the end of app/build.gradle
> 
> ```
> allprojects {
>     repositories {
>         //start here
>         configurations.all {
>             resolutionStrategy.eachDependency { DependencyResolveDetails details ->
>                 def requested = details.requested
>                 if (requested.group == 'com.google.android.gms') {
>                     details.useVersion '12.0.1'
>                 }
>                 if (requested.group == 'com.google.firebase') {
>                     details.useVersion '12.0.1'
>                 }
>             }
>         }
>         //end
>         jcenter()
>         maven {
>             url "https://maven.google.com"
>         }
>     }
> }
> ```
> 
> I'm not using firebase.
> The problem occurs on a real Android device, it works on the iOS emulator.

ohhh Goood! thanks!! @Gioxxy
